# Generated by Django 6.0.4 on 2026-04-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('kode_cust', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_cust', models.CharField(max_length=200)),
                ('wilayah', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('kode_barang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=200)),
                ('harga_jual', models.IntegerField()),
                ('stok_saat_ini', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('nomor_faktur', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('status_pembayaran', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('harga_satuan', models.IntegerField(editable=False)),
                ('subtotal', models.IntegerField(editable=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.product')),
            ],
        ),
    ]
