# Generated by Django 6.0.4 on 2026-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='no_telp',
        ),
        migrations.AddField(
            model_name='invoice',
            name='diskon_persen',
            field=models.IntegerField(default=0, help_text='Isi dengan angka, contoh: 10 untuk 10%'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ppn_persen',
            field=models.IntegerField(default=0, help_text='Isi dengan angka, contoh: 11 untuk 11%'),
        ),
    ]
