# Generated by Django 6.0.4 on 2026-04-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_customer_no_telp_invoice_diskon_persen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tempo_hari',
            field=models.IntegerField(default=30, help_text='Batas pembayaran dalam hari (Contoh: 30 untuk 1 bulan, 60 untuk 2 bulan)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='diskon_persen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ppn_persen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tanggal_jatuh_tempo',
            field=models.DateField(blank=True, help_text='Kosongkan agar terisi otomatis berdasarkan aturan Customer', null=True),
        ),
    ]
