# Generated by Django 6.0.4 on 2026-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_tempo_hari_alter_invoice_diskon_persen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tempo_hari',
            field=models.IntegerField(default=60, help_text='Batas pembayaran dalam hari (Contoh: 30 untuk 1 bulan, 60 untuk 2 bulan)'),
        ),
    ]
