# Generated by Django 6.0.4 on 2026-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_tempo_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='nomor_faktur',
            field=models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
