# Generated by Django 6.0.4 on 2026-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_invoice_nomor_faktur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='harga_satuan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
