# Generated by Django 6.0.4 on 2026-04-25 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_invoiceitem_harga_satuan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
