# Generated by Django 6.0.4 on 2026-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_invoice_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], max_length=5, null=True, verbose_name='Kode Sales'),
        ),
    ]
