# Generated by Django 6.0.4 on 2026-05-06 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoice_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Masuk)'), ('OUT', 'Stock Out (Keluar)')], max_length=3)),
                ('qty', models.PositiveIntegerField()),
                ('reference', models.CharField(help_text='Nomor Faktur, Surat Jalan, atau Referensi PO', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='sales.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
