# Generated by Django 6.0.4 on 2026-05-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=100, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('rekening_bank', models.CharField(blank=True, help_text='Contoh: BCA a/n PT MITRA RAJA 123456', max_length=200, null=True)),
            ],
        ),
    ]
