# Generated by Django 6.0.4 on 2026-05-06 16:29

from django.db import migrations

def preload_suppliers(apps, schema_editor):
    Supplier = apps.get_model('sales', 'Supplier') # <-- CHANGE 'nama_app_kamu' to your app name
    
    companies = [
        "PT MITRA RAJA ANUGERAH",
        "CV KARYA RAJA ANUGRAH",
        "COLOR KING",
        "COLOUR MASTER"
    ]
    for company in companies:
        Supplier.objects.get_or_create(nama_supplier=company)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_supplier'),
    ]

    operations = [
        migrations.RunPython(preload_suppliers, migrations.RunPython.noop),
    ]
