# Generated by Django 6.0.4 on 2026-05-06 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20260506_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_faktur', models.CharField(max_length=50, unique=True)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('subtotal', models.IntegerField(default=0)),
                ('grand_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('harga_beli', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('restock_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.restockinvoice')),
            ],
        ),
    ]
