# Generated by Django 6.0.4 on 2026-05-06 23:50

from django.db import migrations


def preload_suppliers(apps, schema_editor):
    Supplier = apps.get_model('sales', 'Supplier')
    companies = [
        "PT MITRA RAJA ANUGERAH",
        "CV KARYA RAJA ANUGRAH",
        "COLOR KING",
        "COLOUR MASTER",
    ]
    for company in companies:
        Supplier.objects.get_or_create(nama_supplier=company)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_restockinvoice_restockitem'),
    ]

    operations = [
        migrations.RunPython(preload_suppliers, migrations.RunPython.noop),
    ]
