# Generated by Django 6.0.4 on 2026-05-06 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_add_default_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockinvoice',
            name='tanggal',
            field=models.DateField(default=django.utils.timezone.now, help_text='Tanggal di kertas faktur'),
        ),
        migrations.AlterField(
            model_name='restockinvoice',
            name='tanggal_jatuh_tempo',
            field=models.DateField(help_text='Tgl J/T (Kredit 60 Hari)'),
        ),
        migrations.AlterField(
            model_name='restockitem',
            name='harga_beli',
            field=models.IntegerField(blank=True, default=0, help_text='Harga modal dari pabrik', null=True),
        ),
        migrations.AlterField(
            model_name='restockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.product'),
        ),
        migrations.AlterField(
            model_name='restockitem',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='restockitem',
            name='subtotal',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
