# Generated by Django 6.0.4 on 2026-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_restockinvoice_tanggal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.CharField(blank=True, help_text='Terisi otomatis dari Kode Barang (contoh: TH, NC)', max_length=20, null=True),
        ),
    ]
