# Generated by Django 6.0.4 on 2026-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_product_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nomor_resi',
            field=models.CharField(blank=True, help_text='Contoh: JNE - 10293848 atau Supir Budi', max_length=100, null=True),
        ),
    ]
