# Generated by Django 6.0.4 on 2026-05-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_invoice_nomor_resi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_telp',
            field=models.CharField(blank=True, help_text='Contoh: 0812-3456-7890', max_length=20, null=True),
        ),
    ]
