# Generated by Django 6.0.4 on 2026-05-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_customer_no_telp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nama_transaksi', models.CharField(max_length=200)),
                ('jenis_transaksi', models.CharField(choices=[('IN', 'Pemasukan'), ('OUT', 'Pengeluaran')], max_length=3)),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status_pembayaran', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='LUNAS', max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice')),
            ],
            options={
                'verbose_name_plural': 'Cashflow',
                'ordering': ['-tanggal'],
            },
        ),
    ]
