# Generated by Django 6.0.4 on 2026-05-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='restock_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.restockinvoice'),
        ),
    ]
