# Generated by Django 6.0.4 on 2026-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_cashflow_restock_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockinvoice',
            name='status_pembayaran',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], default='Belum Lunas', max_length=20),
        ),
    ]
