# Generated by Django 6.0.4 on 2026-05-18 02:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_restockinvoice_status_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('output_qty', models.PositiveIntegerField(verbose_name='Jumlah Hasil')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('output_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='readymix_outputs', to='sales.product', verbose_name='Produk Hasil')),
            ],
            options={
                'verbose_name': 'Ready Mix',
                'verbose_name_plural': 'Ready Mix',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadyMixIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Jumlah Dipakai')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='readymix_uses', to='sales.product', verbose_name='Bahan')),
                ('ready_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='sales.readymix')),
            ],
        ),
    ]
