# Generated by Django 6.0.4 on 2026-05-20 00:42

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_readymix_data(apps, schema_editor):
    ReadyMix = apps.get_model('sales', 'ReadyMix')
    ReadyMixOutput = apps.get_model('sales', 'ReadyMixOutput')
    for rm in ReadyMix.objects.all():
        if rm.output_product_id and rm.output_qty:
            ReadyMixOutput.objects.create(
                ready_mix=rm,
                product_id=rm.output_product_id,
                qty=rm.output_qty
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_readymix_readymixingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readymix',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ready Mix / Moving', 'verbose_name_plural': 'Ready Mix / Moving'},
        ),
        migrations.AddField(
            model_name='readymix',
            name='jenis',
            field=models.CharField(choices=[('Ready Mix', 'Ready Mix'), ('Moving', 'Moving / Pemindahan')], default='Ready Mix', max_length=20, verbose_name='Jenis Transaksi'),
        ),
        migrations.AlterField(
            model_name='readymix',
            name='output_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='readymix_outputs', to='sales.product', verbose_name='Produk Hasil (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='readymix',
            name='output_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jumlah Hasil (Deprecated)'),
        ),
        migrations.CreateModel(
            name='ReadyMixOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Jumlah Hasil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='readymix_outputs_items', to='sales.product', verbose_name='Produk Hasil')),
                ('ready_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='sales.readymix')),
            ],
        ),
        migrations.RunPython(migrate_existing_readymix_data),
        migrations.RemoveField(
            model_name='readymix',
            name='output_product',
        ),
        migrations.RemoveField(
            model_name='readymix',
            name='output_qty',
        ),
    ]
