# Generated by Django 6.0.4 on 2026-05-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_readymix_options_readymix_jenis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='readymix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sales.readymix'),
        ),
    ]
