# Generated by Django 6.0.4 on 2026-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readymix',
            name='catatan',
        ),
        migrations.AddField(
            model_name='readymix',
            name='nomor_faktur',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Faktur'),
        ),
    ]
