# Generated by Django 6.0.4 on 2026-05-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_remove_readymix_catatan_readymix_nomor_faktur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kode_cust',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wilayah',
            field=models.CharField(choices=[('Jawa Tengah', 'Jawa Tengah (JT)'), ('Jawa Barat', 'Jawa Barat (JB)')], max_length=100),
        ),
    ]
