# Generated by Django 6.0.4 on 2026-05-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harga_beli',
            field=models.IntegerField(default=10000, help_text='Harga modal dari pabrik (terisi otomatis dari restock terakhir)'),
        ),
    ]
