# Generated by Django 6.0.4 on 2026-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_add_harga_beli_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kode_sales',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], help_text='Sales yang akan otomatis terisi saat membuat faktur baru untuk customer ini', max_length=5, null=True, verbose_name='Kode Sales'),
        ),
    ]
