# Generated by Django 6.0.4 on 2026-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_customer_kode_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-tanggal', '-nomor_faktur']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='sudah_cetak',
            field=models.BooleanField(default=False, help_text='Centang jika faktur ini sudah dicetak', verbose_name='Sudah Cetak'),
        ),
    ]
